#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.5 on Fri Dec 18 17:22:03 2020
#

import wx


class FloatSlider(wx.Panel):
    def __init__(self, parent, value=0.0, minVal=0.0, maxVal=10.0, label="label", id=''):
        super(FloatSlider, self).__init__(parent)
        self.parent = parent
        self.value = value
        self.divisions = 10
        self.freq = 1
        self.minVal = minVal
        self.maxVal = maxVal

        self.label = label
        self.id = id

        # self.panel = wx.Panel(self, wx.ID_ANY)
        self.text_ctrl = wx.TextCtrl(self, wx.ID_ANY, str(self.value), style=wx.TE_CENTRE)
        self.slider = wx.Slider(self, wx.ID_ANY, self.startPosition(), 0, self.divisions,
                                style=wx.SL_AUTOTICKS | wx.SL_HORIZONTAL)
        self.SetRange(self.minVal, self.maxVal)
        # EVENT HANDLES ------------------------------------------------------------------------------------------------
        self.Bind(wx.EVT_SLIDER, self.onSliderChange, self.slider)

        self.__set_properties()
        self.__do_layout()

    def __set_properties(self):
        self.text_ctrl.SetMinSize((40, 23))
        self.text_ctrl.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))

    def __do_layout(self):
        grid_sizer_1 = wx.GridBagSizer(0, 0)
        self.slider_label = wx.StaticText(self, wx.ID_ANY, self.label)
        self.slider_label.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(self.slider_label, (0, 0), (1, 1), wx.ALIGN_CENTER, 0)
        grid_sizer_1.Add(self.text_ctrl, (1, 0), (1, 1), 0, 0)
        grid_sizer_1.Add(self.slider, (1, 1), (1, 1), wx.ALIGN_BOTTOM | wx.EXPAND, 0)
        # self.panel.SetSizer(grid_sizer_1)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.AddGrowableCol(1)

    def startPosition(self):
        return int((self.value * self.divisions))

    def SetRange(self, minValue, maxValue):
        self.minVal = minValue
        self.maxVal = maxValue

        self.slider.SetMin(0)
        self.slider.SetMax(self.divisions)

    def SetTickFreq(self, freq):
        divisions = int((self.maxVal - self.minVal) / freq)
        if divisions >= 2:
            self.divisions = divisions
        self.freq = (self.maxVal - self.minVal) / divisions
        self.slider.SetTickFreq(1)

    def GetValue(self):
        self.value = round((self.slider.GetValue() / self.divisions) * self.maxVal, 2)
        return self.value

    def SetValue(self, value):
        self.value = value
        self.slider.SetValue(int(((self.value / self.maxVal) * self.divisions)))
        self.change_text(self.value)

    def onSliderChange(self, event):
        value = self.GetValue()
        self.change_text(round(value, 2))

        # Child class posts event to the parent class
        # https://stackoverflow.com/a/6344425/3382269
        wx.PostEvent(self.parent, event)

    def change_label(self, s):
        self.slider_label.SetLabelText(str(s))

    def change_text(self, s):
        self.text_ctrl.SetValue(str(s))

    def setID(self, id):
        self.id = str(id)

    def getID(self):
        return self.id


def report_val(evt, name):
    print(f'{name} has changed to {evt.GetEventObject().GetValue()}')


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 98))
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.slider = FloatSlider(self.panel_1, value=0.5, minVal=0, maxVal=1, label='Kp')

        self.Bind(wx.EVT_SLIDER, lambda event: report_val(event, "Kp"))

        self.__set_properties()
        self.__do_layout()

    def __set_properties(self):
        self.SetTitle("FloatSlider")

    def __do_layout(self):
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        sizer_2.Add(self.slider, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)

        self.SetSizer(sizer_1)
        self.Layout()


class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True


if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
